#端口号
server:
  port: 8080
spring:
  profiles:
    # 配置文件拆分
    # 拆分后的配置文件名格式为:application-xxx.yml,如:application-sharding.yml
    # 多个拆分的配置文件并列添加即可
    include:
      - sharding
  application:
    #服务名称 非必录项
    name: reggie-takeout
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #主键策略：ASSIGN_ID（雪花算法）
      id-type: ASSIGN_ID

reggie:
  file:
    # 图片资源存放路径 目前先存放在项目目录下
    path: /Users/m0v1/IdeaProjects/reggie-takeout/imgs/