#端口号
server:
  port: 8080
spring:
  application:
    #服务名称 非必录项
    name: reggie-takeout
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://remote-srv-dns:13306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: reggie
      password: wAfeATPxYR4SCpbz
  redis:
    host: remote-srv-dns
    port: 16379
    jedis:
      pool:
        # 最大连接数
        max-active: 8
        # 连接池中的最大空闲连接
        max-idle: 4
        # 连接池中最大阻塞等待时间
        max-wait: 1ms
        # 连接池中的最小空闲连接
        min-idle: 0
    # 默认使用0号数据库
    database: 0
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #主键策略：ASSIGN_ID（雪花算法）
      id-type: ASSIGN_ID

reggie:
  file:
    # 图片资源存放路径 目前先存放在项目目录下
    path: /Users/m0v1/IdeaProjects/reggie-takeout/imgs/