spring:
  shardingsphere:
    datasource:
      names:
        master,slave
      # 主数据源名称(自定义名称)
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://remote-srv-dns:13307/reggie?characterEncoding=utf-8
        username: root
        password: master_root_password
      # 从数据源名称(自定义名称)
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://remote-srv-dns:13308/reggie?characterEncoding=utf-8
        username: root
        password: master_root_password
    masterslave:
      # 读写分离配置
      # 轮询
      load-balance-algorithm-type: round_robin
      # 最终的数据源名称
      name: dataSource
      # 主库数据源名称
      master-data-source-name: master
      # 从库数据源名称列表，有多个时使用逗号分隔
      slave-data-source-names: slave
    props:
      sql:
        #开启SQL显示，默认false
        show: true
  main:
    allow-bean-definition-overriding: true